"""drop column

Revision ID: 9ebd6ae7cd68
Revises: e77cc7159aea
Create Date: 2023-03-11 18:44:02.541754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebd6ae7cd68'
down_revision = 'e77cc7159aea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('user_id1')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id1', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
